spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: UserProvider
server:
  port: 9022
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:10086/eureka,http://localhost:10087/eureka